### PR TITLE
update to currently support ruby and rails versions

### PR DESCRIPTION
**Pull request by craig-day**
Okay, here you go @grosser. 

This drops all unsupported versions of ruby and rails, and brings in a few new ones.

### CODE REVIEW

**Comment by grosser** [comment]
nice, also bump ruby + activerecord version in the gemspec :)

**Comment by grosser** [comment]
I guess simplify this to not add rails 5 so we can get it merged ... next PR can add rails 5/6

**Comment by rubiety** [comment]
Thanks for modernizing this, @craig-day. I can merge this, but it looks like we have some failures in CI on this branch related to `rake` - perhaps that needs a version bump too?

https://travis-ci.org/rubiety/validates_lengths_from_database/builds/603132810?utm_source=github_status&utm_medium=notification

**Comment by craig-day** [comment]
@rubiety I updated this. I actually had to restrict to an older version of rake due to some Rspec v2 details. I put a small comment in the gemspec, but this should be good to go!

**Pull request merged**
